### ISSUE TITLE
How to make a transaction and rollback?

### ISSUE THREAD

**Issue by gohsianghwee** [yojimbo87/ArangoDB-NET#11]
Hi Yojimbo87,

I tried to find the word transaction in your test case but couldn't get it. May I know how to make transaction call in your driver? Thanks.

Cordially,
Goh

**Comment by yojimbo87** [comment]
Hi Goh,

transactions API is not yet implemented in the driver. I might work on it during following weekend.

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

Noted with thanks. I shall check again later for the update. Thanks again for your help.

**Comment by yojimbo87** [comment]
Supported in [reimplement](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch.

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

Noted with thanks.
