### ISSUE TITLE
Cannot retrieve data with List<int> property

### ISSUE THREAD

**Issue by gohsianghwee** [yojimbo87/ArangoDB-NET#15]
Hi Yojimbo87,

As reported in the [stackoverflow](http://stackoverflow.com/questions/28104809/arangodb-error-for-listint-type). The class structure is very straightforward. So long you add the `List<int>` or array then it will start prompting error when you try to get the collection. However, data will still be saved but retrieving will cause some issue.

```csharp
public class Employee 
{
    public string Id { get; set; }

    public string Key { get; set; }

    public string Revision { get; set; }


    public string Name { get; set; }

    public string IcNumber { get; set; }

    public string Email { get; set; }

    public string Department { get; set; }
    public double Height { get; set; }

    public DateTime DateOfBirth { get; set; }

    public decimal Salary { get; set; }

    public IList<Phone> Phones { get; set; }

    public List<int> Numbers { get; set; }
}
```

**Comment by yojimbo87** [comment]
Fixed in [reimplement](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch.

**Comment by gohsianghwee** [comment]
Hi Tomas,

Thanks again.
