### ISSUE TITLE
Create Indexes using .NET driver

### ISSUE THREAD

**Issue by AndreasTurowski** [yojimbo87/ArangoDB-NET#20]
I have no classes/methods found to create/manage Indexes. Is this really true? Without creating Indexes from c# code (including fulltext) the driver will be useless for me.

**Comment by yojimbo87** [comment]
Hi, index API is not yet implemented into the driver. I will work on this functionality during this week.

**Comment by AndreasTurowski** [comment]
Sounds good, I'm evaluating NoSQL-Databases for a large Project/product but evalutation process will be finished next week. So i wouldn't Need index Features in production state, but for testing.

**Comment by ifcologne** [comment]
@AndreasTurowski - if you have any questions regarding ArangoDB, please ask the ArangoDB team via hackers AT arangodb.org.

**Comment by fceller** [comment]
@AndreasTurowski if you have any issues you would like to discuss or if we can help you with the evaluation, please contact hackers (at) arangodb.org to discuss matters in detail

**Comment by yojimbo87** [comment]
Implemented in 0.9.2

**Comment by AndreasTurowski** [comment]
That was quickly! I will start testing today.
