### ISSUE TITLE
Is graph  module supported?

### ISSUE THREAD

**Issue by specimen151** [yojimbo87/ArangoDB-NET#31]
I can't find the functions from https://docs.arangodb.com/GeneralGraphs/Management.html anywhere in the API. Is this planned in a future release?

**Comment by yojimbo87** [comment]
HTTP API for [graph module](https://docs.arangodb.com/HttpGharial/index.html) is not yet implemented into the driver. I'll look into it during following week how much work would it require to add this functionality.

**Comment by yojimbo87** [comment]
I looked into the ArangoDB REST API docs and it seems to be straightforward to implement, so this functionality will be supported in the next release.

**Comment by specimen151** [comment]
That's great news!

**Comment by specimen151** [comment]
Closing, this issue is too old, at it was mentioned that it would be included in the next release anyway.
