### ISSUE TITLE
Executing Transacted AQL Query

### ISSUE THREAD

**Issue by odinhaus** [yojimbo87/ArangoDB-NET#41]
Trying to execute an AQL query in a transaction, but keep getting HTTP 400 error.

What am I doing wrong?

Here's my C# code:
```
var action = string.Format("function () {{ var db = require('org/arangodb').db; return db.query(\"{0}\").toArray(); }}", aql).Replace(System.Environment.NewLine, " ");
var model = db.Transaction.WriteCollection(ModelTypeManager.GetModelName(queue.ModelType).Replace(".", "_"))
                              .ReadCollection(ModelTypeManager.GetModelName(queue.ModelType).Replace(".", "_"))
                              .Execute<List<Dictionary<string, object>>>(action).Value.First();
```

And the action text when evaluated is as follows:
`"function () { var db = require('arangojs').db; return db.query('LET q0 = (FOR v0 in Financial_Check FILTER (v0.IsDeleted == false && v0.IsAllocated == false) RETURN v0) FOR r in q0   COLLECT WITH COUNT INTO length RETURN {Count: length}'); }"`

Hope you can help!  Thanks.

**Comment by yojimbo87** [comment]
Is there also some error message which can provide some more information to the HTTP 400 error?

**Comment by odinhaus** [comment]
> ArangoDB error: missing/invalid action definition for transaction - Uncaught SyntaxError: missing ) after argument list - SyntaxError: missing ) after argument list
>     at post_api_transaction (c:\Program Files\ArangoDB 3.0.7\share\arangodb3\js\actions\api-transaction.js:49:16)
>     at Function.actions.defineHttp.callback (c:\Program Files\ArangoDB 3.0.7\share\arangodb3\js\actions\api-transaction.js:66:11)

**Comment by odinhaus** [comment]
I'm using v3.0.7 of ArangoDB

**Comment by yojimbo87** [comment]
If you execute your transaction directly through arango shell it works as expected?

**Comment by odinhaus** [comment]
Seems the " in the 

> return db.query(\"{0}\").toArray();

around the AQL throws everything into a tailspin....

I changed to ' and now it works as expected.

Sorry for wasting your time! lol  How silly.

**Comment by yojimbo87** [comment]
It's ok, good to know what was the solution.
