### ISSUE TITLE
Specified 'id' value (abc.def) has invalid format.

### ISSUE THREAD

**Issue by jeff-pang** [yojimbo87/ArangoDB-NET#44]
```c#
var result = db.Document.Get<UserInfo>($"Users/{userId}");
```
If userId with value "abc.def" is supplied an exception `Specified 'id' value (Users/abc.def) has invalid format.` will be returned. However this is a valid id and using AQL as follows will work

```c#
var result = db.Query
                  .BindVar("userId", userId)
                  .Aql("FOR u in Users FILTER u._key == @userId RETURN u")
                  .ToObject<UserInfo>();
```

**Comment by yojimbo87** [comment]
This seems to be a bug in key format checking regex which doesn't allow some punctuation characters stated in [key naming conventions](https://docs.arangodb.com/3.1/Manual/DataModeling/NamingConventions/DocumentKeys.html). I'll try to fix it today or tomorrow.

**Comment by jeff-pang** [comment]
Thanks but no hurry.

**Comment by yojimbo87** [comment]
[Fixed](https://github.com/yojimbo87/ArangoDB-NET/commit/eafc84fd72267fa8993f2ccaee0d524cbf812059) in master branch.
