### ISSUE TITLE
Convert strongly typed object to document

### ISSUE THREAD

**Issue by Eliakos** [yojimbo87/ArangoDB-NET#52]
It' from the doc https://github.com/yojimbo87/dictator#convert-document-to-strongly-typed-object
When this code is used : 
var dummy = new Dummy();
dummy.Foo = "string value";
dummy.Bar = 12345;

var document = Dictator.ToDocument(dummy);

but on "var dummy = new Dummy();", 
I get CS0246  C# The type or namespace name could not be found (are you missing a using directive or an assembly reference?)

Even if I declared "using Arango.Client;"
I tried to download dictator fro github, reference it into my project and using it but it conflicts with Arango.Client.

Any idea ?

**Comment by yojimbo87** [comment]
Hi, Dummy is just sample POCO with two properties (Foo as string and Bar as integer value). It serves as an example of strongly typed object conversion.

**Comment by Eliakos** [comment]
Yes, i realized and use my poco just after
As a beginner in c# and arango, there is a delay to understand... :)

Thank you for taking time to answer
