### ISSUE TITLE
hydrating array property throw "No parameterless constructor defined for this object." 

### ISSUE THREAD

**Issue by jeff-pang** [yojimbo87/ArangoDB-NET#7]
Error thrown when using db.Query.Aql(aql).ToObject<SomeClass>() where SomeClass Contains an array property e.g
![screenshot at jan 11 17-09-25](https://cloud.githubusercontent.com/assets/1246546/5694775/bf4a9478-99b4-11e4-8e1f-d8ab4d4ab4f6.png)

The error occurs in Document.cs line 1837:
var instance = Activator.CreateInstance(propertyInfo.PropertyType);

**Comment by yojimbo87** [comment]
Fixed in [reimplement](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch.
