### ISSUE TITLE
Reimplement version issue

### ISSUE THREAD

**Issue by gohsianghwee** [yojimbo87/ArangoDB-NET#8]
Hi,

I am using the reimplement version of ArangoDB-Net and figure out few issues.

1. My sampleClass has a property called Id and it is Guid type and it will be overwritten each time with some hash key. Here's the example: gS9x31usuUu4AtzxbXxv6g==. I find no ArangoProperty anymore. How to define if this is the case?

2. Since the Id is Guid type, it also prompted me the message "Invalid cast from System.String to System.Guid"

Thanks for taking time to answer my question. 

Cordially,
Goh

**Comment by yojimbo87** [comment]
Hi Goh,

1). Reimplement branch has now [three attributes](https://github.com/yojimbo87/dictator#property-attributes) which can be used to flag class properties. If you want to flag some of them as your document ID, then you can try to use `AliasField` attribute like this:

```csharp
public class Dummy
{
    [AliasField("_id")]
    public string Id { get; set; }
}
```

2). There is a restriction for the `_id` field to be in string format `<collection>/<key>`, where key needs to have integer value. I'm going to change this so that it supports [documented](https://docs.arangodb.com/NamingConventions/DocumentKeys.html) restrictions to values which can be used as keys.

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

Noted with thanks. However, I find out the problem is not the _id. In fact, so long the column is guid type it will throw the casting error whenever get or store into haskkey value. Anyway, I have changed all my guid type properties to string at this moment to solve the problem temporary. Thanks again for support.

**Comment by yojimbo87** [comment]
If the property itself is defined as guid type and you are trying to overwrite its value with some hash string then the error should be thrown because e.g. "gS9x31usuUu4AtzxbXxv6g==" is not a valid guid value for the property.

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

Not at all, I stored the value in Guid for sure. However, it turn out to be a hashkey like this gS9x31usuUu4AtzxbXxv6g==. This is something I am not quite sure how it happen. It is a simple demo test class as I have not put any production code in yet.

**Comment by yojimbo87** [comment]
Oh I think I got it wrong. So the value you want to work with is guid, but it is somehow converted to hash value?

**Comment by gohsianghwee** [comment]
Yes. That was exactly what happen.

**Comment by yojimbo87** [comment]
In that case it's weird behavior. Can you provide some simple example?

**Comment by gohsianghwee** [comment]
Hi. I have created a sample

 class Program
    {
        static void Main(string[] args)
        {
            TestNoSqlConcurrentAccess();
            Console.ReadLine();
        }

        public static void TestNoSqlConcurrentAccess()
        {
            ASettings.AddConnection("_system", "127.0.0.1", 8529, false, "_system");
            var db = new ADatabase("_system");
            db.Create("trial_sample");

            ASettings.AddConnection("trial_sample", "127.0.0.1", 8529, false, "trial_sample");
            var db2 = new ADatabase("trial_sample");
            

            
            var demo = new DemoEmployee();
            demo.SomeOtherId = Guid.NewGuid();
            demo.Name = "My name";
            var result = db2.Document.Create<DemoEmployee>("someCollection", demo);
            

        }

    
    }

    public class DemoEmployee
    {
        public Guid SomeOtherId { get; set; }

        public string Name { get; set; }
    }

The result:

{
  "SomeOtherId": "Px4hoawcjk61VybTldRu1g==",
  "Name": "My name"
}

**Comment by gohsianghwee** [comment]
By the way, I am using ArangoDb 2.3.4

**Comment by yojimbo87** [comment]
Fixed in [reimplement](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch.

**Comment by gohsianghwee** [comment]
Tested and it works now
