### ISSUE TITLE
Enum type handling

### ISSUE THREAD

**Issue by gohsianghwee** [yojimbo87/ArangoDB-NET#9]
Hi Yojimbo87,

One of the reason to use this reimplement is because of enum handling. However, I could not implement the enum correctly. Could you point out if I have done anything wrong? Thanks.

Here's the code:

```csharp
public static void Demo()
{
    //ASettings.AddConnection("_system", "127.0.0.1", 8529, false, "_system");
    //var db = new ADatabase("_system");
    //db.Create("trial_sample");

    ASettings.AddConnection("trial_sample", "127.0.0.1", 8529, false, "trial_sample");
    var db2 = new ADatabase("trial_sample");
    db2.Collection.Create("someCollection");

    
    var demo = new DemoEmployee();
    demo.SomeOtherId = Guid.NewGuid();
    demo.Name = "My name";
    demo.MyFavoriteColor = DemoEmployee.Color.Blue;
    var result = db2.Document.Create<DemoEmployee>("someCollection", demo);

    // Error for invalid casting from string to int
    var myDemo = db2.Document.Get<DemoEmployee>(result.Value.String("_id"));

    Console.WriteLine(myDemo.Value.MyFavoriteColor);
}

public class DemoEmployee
{
    public Guid SomeOtherId { get; set; }

    public string Name { get; set; }

    public Color MyFavoriteColor { get; set; }
    public enum Color
    {
        Blue, Red
    }
}
```

Here's the result after storing. 

```
{
  "MyFavoriteColor": "Blue",
  "SomeOtherId": "9a195968-e60f-4dd1-8ac2-cc0a59f1dbe9",
  "Name": "My name"
}
```

Thanks again for your help

**Comment by yojimbo87** [comment]
Fixed in [reimplement](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch. Now you can also setup your custom [serialization options](https://github.com/yojimbo87/ArangoDB-NET/blob/reimplement/docs/BasicUsage.md#serialization-options) which are available in fastJSON library, for example serializing enums in database as integers which might be more efficient and convenient.

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

I am not sure if I have comprehend it correctly. I cannot find the ASettings.JsonParameters as mentioned in the serialization options section. Would you mind to show me some example? Thanks.

**Comment by yojimbo87** [comment]
Have you pulled the latest changes in reimplement branch and built it? Example can be found in [this test method](https://github.com/yojimbo87/ArangoDB-NET/blob/reimplement/src/Arango/Arango.Tests/Issues/IssueTests.cs#L64).

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

Thanks. The problem is now solve. I pulled it yesterday night but only reported today. The problem has been resolved. Thanks again for your promptly support.
